# Agent Role Categories
categories = {
    "Network Infrastructure Agents": "Agents representing network components like base stations, routers, edge servers, etc.",
    "Vehicle & Transportation Agents": "Agents related to vehicles, UAVs, and transportation systems",
    "Digital Twin & Metaverse Agents": "Agents representing digital twins or operating in metaverse environments",
    "IoT & Industrial Agents": "Agents in IoT systems, industrial environments, or physical process control",
    "Learning & Optimization Agents": "Agents focused on machine learning, optimization, or decision-making",
    "Social & Human Interaction Agents": "Agents representing humans or social interactions"
}

agent_roles = {
    1: "Network Infrastructure",
    2: "Network Infrastructure",
    3: "Digital Twin",
    4: "Digital Twin",
    5: "Learning",
    6: "Network Infrastructure",
    7: "Transportation",
    8: "Transportation",
    9: "Transportation",
    10: "Network Infrastructure",
    11: "Network Infrastructure",
    12: "IoT Industrial",
    13: "Digital Twin",
    14: "Digital Twin",
    15: "Digital Twin",
    16: "Digital Twin",
    17: "Digital Twin",
    18: "Network Infrastructure",
    19: "IoT Industrial",
    20: "Network Infrastructure",
    21: "Transportation",
    22: "Network Infrastructure",
    23: "Network Infrastructure",
    24: "Social Interaction",
    25: "Transportation",
    26: "Social Interaction",
    27: "Social Interaction",
    28: "Network Infrastructure",
    29: "Learning",
    30: "Digital Twin",
    31: "Digital Twin",
    32: "Digital Twin",
    33: "Digital Twin",
    34: "Learning",
    35: "Social Interaction",
    36: "Digital Twin",
    37: "Learning",
    38: "Network Infrastructure",
    39: "Learning",
    40: "Network Infrastructure",
    41: "Network Infrastructure",
    42: "Network Infrastructure",
    43: "IoT Industrial",
    44: "Network Infrastructure",
    45: "Learning",
    46: "Digital Twin",
    47: "Transportation",
    48: "Social Interaction",
    49: "Transportation",
    50: "Transportation",
    51: "Transportation",
    52: "Transportation",
    53: "Transportation",
    54: "Transportation",
    55: "Network Infrastructure",
    56: "Social Interaction",
    57: "Social Interaction",
    58: "Social Interaction",
    59: "Social Interaction",
    60: "Social Interaction",
    61: "Social Interaction",
    62: "Network Infrastructure",
    63: "Social Interaction",
    64: "Network Infrastructure",
    65: "Transportation",
    66: "Transportation",
    67: "Network Infrastructure",
    68: "Network Infrastructure",
    69: "Network Infrastructure",
    70: "Network Infrastructure",
    71: "Network Infrastructure",
    72: "Digital Twin",
    73: "Network Infrastructure",
    74: "Network Infrastructure",
    75: "Network Infrastructure",
    76: "Network Infrastructure",
    77: "Digital Twin",
    78: "Digital Twin",
}
