# Behavior Mechanism Categories
categories = {
    "Reinforcement Learning & MARL": "Techniques involving reinforcement learning, multi-agent reinforcement learning, and related algorithms",
    "Game Theory & Optimization": "Approaches using game theory, optimization methods, and mathematical modeling",
    "Hybrid AI Techniques": "Combinations of different AI methods or AI with other computational techniques",
    "Distributed & Federated Systems": "Mechanisms involving distributed computing, federated learning, or decentralized architectures",
    "Simulation & Modeling": "Methods focused on simulation, modeling, and virtual environments"
}

behavior_mechanisms = {
    1: "Reinforcement Learning",
    2: "Hybrid AI Techniques",
    3: "Hybrid AI Techniques",
    4: "Game Theory",
    5: "Reinforcement Learning",
    6: "Reinforcement Learning",
    7: "Reinforcement Learning",
    8: "Reinforcement Learning",
    9: "Reinforcement Learning",
    10: "Game Theory",
    11: "Reinforcement Learning",
    12: "Game Theory",
    13: "Hybrid AI Techniques",
    14: "Hybrid AI Techniques",
    15: "Hybrid AI Techniques",
    16: "Game Theory",
    17: "Game Theory",
    18: "Reinforcement Learning",
    19: "Reinforcement Learning",
    20: "Reinforcement Learning",
    21: "Hybrid AI Techniques",
    22: "Reinforcement Learning",
    23: "Reinforcement Learning",
    24: "Reinforcement Learning",
    25: "Reinforcement Learning",
    26: "Reinforcement Learning",
    27: "Reinforcement Learning",
    28: "Reinforcement Learning",
    29: "Reinforcement Learning",
    30: "Reinforcement Learning",
    31: "Hybrid AI Techniques",
    32: "Reinforcement Learning",
    33: "Reinforcement Learning",
    34: "Reinforcement Learning",
    35: "Game Theory",
    36: "Hybrid AI Techniques",
    37: "Reinforcement Learning",
    38: "Game Theory",
    39: "Reinforcement Learning",
    40: "Game Theory",
    41: "Reinforcement Learning",
    42: "Reinforcement Learning",
    43: "Game Theory",
    44: "Reinforcement Learning",
    45: "Reinforcement Learning",
    46: "Game Theory",
    47: "Reinforcement Learning",
    48: "Reinforcement Learning",
    49: "Game Theory",
    50: "Game Theory",
    51: "Game Theory",
    52: "Reinforcement Learning",
    53: "Reinforcement Learning",
    54: "Reinforcement Learning",
    55: "Reinforcement Learning",
    56: "Game Theory",
    57: "Game Theory",
    58: "Game Theory",
    59: "Game Theory",
    60: "Reinforcement Learning",
    61: "Game Theory",
    62: "Reinforcement Learning",
    63: "Game Theory",
    64: "Reinforcement Learning",
    65: "Reinforcement Learning",
    66: "Game Theory",
    67: "Reinforcement Learning",
    68: "nan",
    69: "Game Theory",
    70: "Hybrid AI Techniques",
    71: "Hybrid AI Techniques",
    72: "Hybrid AI Techniques",
    73: "Reinforcement Learning",
    74: "Reinforcement Learning",
    75: "Reinforcement Learning",
    76: "Reinforcement Learning",
    77: "Hybrid AI Techniques",
    78: "Reinforcement Learning",
}
